export enum Abilities {
  Logout = 1,
  Change_Password = 2,
  Get_Roles = 3,
  Get_Role = 4,
  Add_Role = 5,
  Delete_Role = 6,
  Update_Role = 7,
  Get_User_Roles = 8,
  Update_User_Roles = 9,
  Get_Patient_Info = 10,
  Get_Patient_History_Notes = 11,
  Get_Patient_History_Chief_Complaints = 12,
  Save_Patient_History = 13,
  Get_Allergies = 14,
  Get_Patient_Allergies = 15,
  Get_Diagnoses = 16,
  Get_Patient_Diagnoses = 17,
  Get_Signs = 18,
  Get_Patient_Signs = 19,
  Get_Symptoms = 20,
  Get_Patient_Symptoms = 21, 
  Get_Medicines = 22,
  Get_Patient_Medicines = 23
}